### ISSUE TITLE
i can't use array for dataset

### ISSUE THREAD

**Issue by rizki82** [VTwo-Group/Apriori-Algorithm#2]
rellay good work! i like it, but why when i switch to use array for dataset, it give me error  explode() expects parameter 2 to be string

**Comment by rizki82** [comment]
to overcome the limitation, fisrt i write the array to txt and then process the apriori

**Comment by adifahmi** [comment]
You can do that, i'm using array that i pull from the database

I push the data to the empty array

``` php
$item_id = array();
foreach ($order_all as $order) {
    array_push($item_id, $order->item_id);
}
```

and then I can process them

``` php
$Apriori->process($item_id);
```

**Comment by rizki82** [comment]
ooh  like that, oke thank you mas bro
